version: "{build}"

platform:
  - x86
  - x64
environment:
  - GO15VENDOREXPERIMENT: 0

install:
  - set GOPATH=%APPVEYOR_BUILD_FOLDER%
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get -v -t ./...

build_script:
  - go test -v ./...
