version: "{build}"

platform:
  - x86
  - x64

clone_folder: c:\gopath\src\github.com\vlifesystems\rulehunter

environment:
  GOPATH: c:\gopath

install:
  - go version
  - go env
  - go get -v -t ./...

build_script:
  - go test -v ./...
